### ISSUE TITLE
Empty lines are skipped

### ISSUE THREAD

**Issue by noncom** [ATryder/jME-TTF#3]
When a text contains empty lines, `TrueTypeBMPContainer` explicitly skips them, for example https://github.com/ATryder/jME-TTF/blob/master/src/main/java/com/atr/jme/font/shape/TrueTypeBMPContainer.java#L91. But in reality empty lines in a text usually mean that there should be an actual empty line.

Could there be a switch that controls this behavior on and off?

**Comment by ATryder** [comment]
https://github.com/ATryder/jME-TTF/commit/0f59fee9dbee4d831a2daa3e8570c46c7305dcd7
